config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  root "public/homes#top"

  namespace :admin do
    resources :orders,only:[:show, :update]
    resources :customers,only:[:show, :index, :edit, :update]
    resources :genres,only:[:index, :create, :edit, :update]
    resources :items,only:[:new, :index, :show, :create, :edit, :update]
    resources :order_items,only:[:update]
    root "homes#top"
  end

  namespace :public do
    resources :shipping_addresses,only:[:index, :create, :edit, :update,:destroy]
    get 'orders/finish'
    post 'orders/check'
    resources :orders,only:[:new, :index, :create, :show]
    delete 'cart_items/destroy_all'
    resources :cart_items,only:[:index, :create, :update, :destroy]
    resource :customers,only:[:show, :edit]
    patch "customers" => "customers#update", as: "customer"
    get 'customers/check'
    patch 'customers/out'
    get 'items/search'
    resources :items,only:[:show, :index]
    get 'homes/about'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached :image
  belongs_to :item

def tax_include_price
  (item.tax_free_price*1.1).round(0)
end

def subtotal
  tax_include_price*amount
end

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
end

  private
  def cart_item_params
      params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    "#{last_name} #{first_name}"
  end
  
  def full_name_kana
    "#{last_name_kana} #{first_name_kana}"
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_one_attached :image
  has_many :cart_items , dependent: :destroy
  has_many :order_items , dependent: :destroy


  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def tax_include_price
    (tax_free_price*1.1).round(0)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items,dependent: :destroy
  
  def total_price
    total_payment + 800
  end

  def ship_address
    "〒 #{post_code} #{address} #{to_name}"
  end

  enum order_status: {
    wait_deposit: 0, payment_confirm: 1, production: 2, ship_preparation: 3, ship_completion: 4
  }

  enum payment_method: {
    credit_card: 0, transfer: 1
  }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: {
     not_startable: 0, wait_product: 1, in_product: 2, finish_product: 3
  }
  
  def tax_included_price
    (purchace_price*1.1).round(0)
  end
  
  def subtotal
    tax_included_price*amount
  end

  def tax_include_price
    (purchace_price*1.1).round(0)
  end

  def s_total
    tax_include_price*amount
  end

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer
  
  validates :post_code,presence:true,length:{minimum: 7, maximum: 7}
  validates :address ,presence:true
  validates :name,presence:true

  def ship_address
  '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_deleted)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
    @genres = Genre.page(params[:page])
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to request.referrer
  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @orders = Order.page(params[:page])
    @amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
      @items = Item.all
      @items = Item.page(params[:page])
    end

    def new
      @item = Item.new
      @genres = Genre.all

    end

    def show
      @item = Item.find(params[:id])
      @genre = @item.genre
    end

    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(@item.id)
    end

    def edit
      @item = Item.find(params[:id])
      @genres = Genre.all
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    end

    private

    def item_params
      params.require(:item).permit(:image, :name, :introduction, :genre_id, :tax_free_price, :sales_status)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
  end

  def update
      @order = Order.find(params[:id])
      @order.update(order_params)
      @order_items = OrderItem.where(order_id: params[:id])
      if @order.order_status == "payment_confirm"
        @order_items.update_all(making_status: "wait_product")
      end
      flash[:notice] = "注文ステータスが更新されました"
      redirect_to request.referrer
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/_index.html.erb
<table class='table table-hover table-striped table-inverse'style="background-color:gainsboro;">
  
  <thead>
    <tr>
      <th nowrap>会員ID</th>
      <th nowrap>氏名</th>
      <th nowrap>メールアドレス</th>
      <th nowrap>ステータス</th>
    </tr>
  </thead>
  
  <tbody>
    <% customers.each do |customer| %>
      <tr>
        <td nowrap><%= customer.id %></td>
        <td nowrap><u><%= link_to customer.full_name,admin_customer_path(customer.id),class: "text-dark"%></u></td>
        <td nowrap><%= customer.email %></td>
        <td>
        <% if customer.is_deleted == false %>
            <span class="text-success"><strong>有効</strong></span>
        <% else %>
            <span class="text-secondary"><strong>退会</strong></span>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/admin/customers/edit.html.erb
<div class="container mt-5">
   <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
   <div class="row">
     <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
     <div class="col-md-12 offset-md-3">
      <table class="table mt-5">
        <tbody>
          <tr>
            <th><%= f.label :id, "会員ID" %></th>
            <th><%= @customer.id %></th>
            <th></th>
          </tr>
          <tr>
            <th><%= f.label :last_name, "氏名" %></th>
            <th><%= f.text_field :last_name %></th>
            <th><%= f.text_field :first_name %></th>
          </tr>
          <tr>
            <th><%= f.label :last_name_kana, "フリガナ" %></th>
            <th><%= f.text_field :last_name_kana %></th>
            <th><%= f.text_field :first_name_kana %></th>
          </tr>
          <tr>
            <th><%= f.label :post_code, "郵便番号" %></th>
            <th><%= f.number_field :post_code %></th>
          </tr>
          <tr>
            <th><%= f.label :address, "住所" %></th>
            <th><%= f.text_field :address %></th>
          </tr>
          <tr>
            <th><%= f.label :phone_number, "電話番号" %></th>
            <th><%= f.number_field :phone_number %></th>
          </tr>
          <tr>
            <th><%= f.label :email, "メールアドレス" %></th>
            <th><%= f.text_field :email %></th>
          </tr>
          <tr>
            <th><%= f.label :is_deleted, "会員ステータス" %></th>
            <th><%= f.radio_button :is_deleted, 0, checked: true %>有効 <%= f.radio_button :is_deleted, 1 %>退会</th>
          </tr>
          <tr>
            <th></th>
            <th><%=  f.submit "変更を保存", class: "btn btn-success btn-lg" %></th>
            <th></th>
          </tr>
        </tbody>
      </table>
     </div>
     <% end %>
   </div>
 </div>

app/views/admin/customers/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class= "pt-5 ml-4 col-md-2 col-sm-6" style="font-size: 20px;">
      <span style="background-color:gainsboro"><strong>　会員一覧　</strong></span>
    </div>
  </div>
  <div class='row ml-5'>
    <div class='pt-4 ml-3 col-md-2 col-sm-6'>
      <%= render 'index', customers: @customers %>
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container mt-5">
   <div class="row">
     <div class="col-md-8 offset-md-1">
       <h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
        <table class="table mt-5">
        <tbody>
          <tr>
            <th>会員ID</th>
            <th><%= @customer.id %></th>
          </tr>
          <tr>
            <th>氏名</th>
            <th><%= @customer.last_name %>　<%= @customer.first_name %></th>
          </tr>
          <tr>
            <th>フリガナ</th>
            <th><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></th>
          </tr>
          <tr>
            <th>郵便番号</th>
            <th><%= @customer.post_code %></th>
          </tr>
          <tr>
            <th>住所</th>
            <th><%= @customer.address %></th>
          </tr>
          <tr>
            <th>電話番号</th>
            <th><%= @customer.phone_number %></th>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <th><%= @customer.email %></th>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <th>
              <% if @customer.is_deleted == false %>
                <span class="text-success">有効</span>
              <% else %>
                <span class="text-danger">退会</span>
              <% end %>
            </th>
          </tr>
          <tr>
            <th></th>
            <th><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success btn-lg mr-5" %><%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-primary btn-lg" %></th>
          </tr>
        </tbody>
      </table>
     </div>
   </div>
 </div>