config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  root "public/homes#top"

  namespace :admin do
    resources :orders,only:[:show, :update]
    resources :customers,only:[:show, :index, :edit, :update]
    resources :genres,only:[:index, :create, :edit, :update]
    resources :items,only:[:new, :index, :show, :create, :edit, :update]
    resources :order_items,only:[:update]
    root "homes#top"
  end

  namespace :public do
    resources :shipping_addresses,only:[:index, :create, :edit, :update,:destroy]
    get 'orders/finish'
    post 'orders/check'
    resources :orders,only:[:new, :index, :create, :show]
    delete 'cart_items/destroy_all'
    resources :cart_items,only:[:index, :create, :update, :destroy]
    resource :customers,only:[:show, :edit]
    patch "customers" => "customers#update", as: "customer"
    get 'customers/check'
    patch 'customers/out'
    get 'items/search'
    resources :items,only:[:show, :index]
    get 'homes/about'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached :image
  belongs_to :item

def tax_include_price
  (item.tax_free_price*1.1).round(0)
end

def subtotal
  tax_include_price*amount
end

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
end

  private
  def cart_item_params
      params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    "#{last_name} #{first_name}"
  end
  
  def full_name_kana
    "#{last_name_kana} #{first_name_kana}"
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_one_attached :image
  has_many :cart_items , dependent: :destroy
  has_many :order_items , dependent: :destroy


  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def tax_include_price
    (tax_free_price*1.1).round(0)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items,dependent: :destroy
  
  def total_price
    total_payment + 800
  end

  def ship_address
    "〒 #{post_code} #{address} #{to_name}"
  end

  enum order_status: {
    wait_deposit: 0, payment_confirm: 1, production: 2, ship_preparation: 3, ship_completion: 4
  }

  enum payment_method: {
    credit_card: 0, transfer: 1
  }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: {
     not_startable: 0, wait_product: 1, in_product: 2, finish_product: 3
  }
  
  def tax_included_price
    (purchace_price*1.1).round(0)
  end
  
  def subtotal
    tax_included_price*amount
  end

  def tax_include_price
    (purchace_price*1.1).round(0)
  end

  def s_total
    tax_include_price*amount
  end

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer
  
  validates :post_code,presence:true,length:{minimum: 7, maximum: 7}
  validates :address ,presence:true
  validates :name,presence:true

  def ship_address
  '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
    @genres = Genre.page(params[:page])
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to request.referrer
  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @orders = Order.page(params[:page])
    @amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
      @items = Item.all
      @items = Item.page(params[:page])
    end

    def new
      @item = Item.new
      @genres = Genre.all

    end

    def show
      @item = Item.find(params[:id])
      @genre = @item.genre
    end

    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(@item.id)
    end

    def edit
      @item = Item.find(params[:id])
      @genres = Genre.all
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    end

    private

    def item_params
      params.require(:item).permit(:image, :name, :introduction, :genre_id, :tax_free_price, :sales_status)
    end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: params[:id])
  end

  def update
      @order = Order.find(params[:id])
      @order.update(order_params)
      @order_items = OrderItem.where(order_id: params[:id])
      if @order.order_status == "payment_confirm"
        @order_items.update_all(making_status: "wait_product")
      end
      flash[:notice] = "注文ステータスが更新されました"
      redirect_to request.referrer
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    super
    flash.delete(:notice)
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/_index.html.erb
<table class='table table-hover table-striped table-inverse'style="background-color:gainsboro;">
  
  <thead>
    <tr>
      <th nowrap>ジャンル</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  
  <tbody>
    <% genres.each do |genre| %>
      <tr>
        <td nowrap><%= genre.name %></td>
        <td nowrap><%= link_to "編集する",edit_admin_genre_path(genre.id),class: "btn btn-success text-white ml-5"%></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class= "col-md-6 mt-5">
      <h4>ジャンル編集</h4>
      <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
      <table class="table mt-5">
         <tr>
           <td>
              <%= f.label :name, "ジャンル名" %>
           </td>
           <td>
              <%= f.text_field :name, class: "form-control" %>
           </td>
           <td>
              <%= f.submit "変更を保存", class: "btn btn-success" %>
           </td>
         </tr>
       </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb

<div class='container px-5 px-sm-0'>
  
  <div class='row'>
    <div class= "pt-5 ml-4 col-md-4 col-sm-6" style="font-size: 20px;">
      <span style="background-color:gainsboro"><strong>　ジャンル一覧・追加　</strong></span>
    </div>
  </div>
    
  <%= form_with model:@genre,url: admin_genres_path, method: :post do |f| %>
  <div class='container px-5 px-sm-0 '>
    <div class='row'>
      <div class="mt-5"><%= f.label :name, "ジャンル名" %></div>
      <div class="mt-5 ml-3 col-3 "><%= f.text_field :name, autofocus: true, autocomplete: "genres", placeholder: "ジャンル名", class:"form-control" %></div>
      <div class="mt-5 ml-3 col-3"><%= f.submit "新規登録", class:"btn btn-success col-5" %></div>
    </div>
  </div>
  <% end %>
  
  <div class='container px-1 px-sm-0 mt-5'>
    <div class='row'>
      <div class="col-3">
      <%= render 'index', genres: @genres %>
      <%= paginate @genres %>
    </div>
   </div>
  </div>


app/views/admin/items/_index.html.erb
<table class='table table-hover table-striped table-inverse'style="background-color:gainsboro;">

  <thead>
    <tr>
      <th nowrap>商品ID</th>
      <th nowrap>商品名</th>
      <th nowrap>税抜価格</th>
      <th nowrap>ジャンル</th>
      <th nowrap >ステータス</th>
    </tr>
  </thead>
  
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id  %></td>
        <td nowrap><u><%= link_to item.name ,admin_item_path(item.id), class: "text-dark"  %></u></td>
        <td><%= item.tax_free_price %></td>
        <td nowrap><%= item.genre.name %></td>
        <td nowrap>
        <% if item.sales_status == false %>
            <span class="text-success"><strong>販売中</strong></span>
        <% else %>
            <span class="text-secondary"><strong>販売停止中</strong></span>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h4>商品編集</h4>
      <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
        <div class="form-group">
          <label for="image">商品画像</label>
          <%= f.file_field :image, accept: "image/*", id: "image", class: "form-control-file image" %>
        </div>
        <div class="form-group">
          <%= f.label :name, "商品名：" %>
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <span>商品説明</span>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <span>ジャンル</span>
          <%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "--選択してください--"}, {class: "form-control input-sm"} %>
        </div>
        <div class="form-group">
          <span>税抜価格</span>
          <%= f.number_field :tax_free_price, class: "form-control" %>円
        </div>
        <div class="form-group">
          <span>販売ステータス</span>
          <%= f.radio_button :sales_status, 0, checked: true %>販売中 <%= f.radio_button :sales_status, 1 %>販売停止中
        </div>
        <div class="form-group">
          <%= f.submit "変更を保存", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class= "pt-5 ml-4 col-md-2 col-sm-6" style="font-size: 20px;">
      <span style="background-color:gainsboro"><strong>　商品一覧　</strong></span>
    </div>
    <div class= "pt-4 ml-auto col-md-3">
      <%= link_to new_admin_item_path do %>
        <i class="fas fa-plus-circle fa-3x" style="color: dimgray;"></i>
      <% end %>
    </div>
  </div>
  <div class='row ml-5'>
    <div class='pt-4 ml-3 col-md-2 col-sm-6'>
      <%= render 'index', item: @item %>
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h4>商品新規登録</h4>
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
        <div class="form-group">
          <label for="image">商品画像</label>
          <%= f.file_field :image, accept: "image/*", id: "image", class: "form-control-file image" %>
        </div>
        <div class="form-group">
          <%= f.label :name, "商品名：" %>
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <span>商品説明</span>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <span>ジャンル</span>
          <%= f.collection_select :genre_id, @genres, :id, :name, {prompt: "--選択してください--"}, {class: "form-control input-sm"} %>
        </div>
        <div class="form-group">
          <span>税抜価格</span>
          <%= f.number_field :tax_free_price, class: "form-control" %>円
        </div>
        <div class="form-group">
          <span>販売ステータス</span>
          <%= f.radio_button :sales_status, 0, checked: true %>販売中 <%= f.radio_button :sales_status, 1 %>販売停止中
        <div class="form-group">
          <%= f.submit "新規登録", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class= "pt-5 ml-4 col-md-2 col-sm-6" style="font-size: 20px;">
      <span style="background-color:gainsboro"><strong>　商品詳細　</strong></span>
    </div>
  </div>
</div>


<div class="container mt-5">
   <div class="row">
     <div class="col-md-3">
       <%= image_tag @item.get_image(200, 200) %>
     </div>

     <div class="col-md-8 offset-md-1">
        <table class="table">
        <tbody>
          <tr>
            <th>商品名</th>
            <th><%= @item.name %></th>
          </tr>
          <tr>
            <th>商品説明</th>
            <th><%= @item.introduction %></th>
          </tr>
          <tr>
            <th>ジャンル</th>
            <th><%= @genre.name %></th>
          </tr>
          <tr>
            <th>税込価格<br>(税抜価格)</th>
            <th><%= (@item.tax_free_price * 1.1).round(0) %>(<%= @item.tax_free_price %>)円</th>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <th>
              <% if @item.sales_status == false %>
                <span class="text-success">販売中</span>
              <% else %>
                <span class="text-secondary">販売停止中</span>
              <% end %>
            </th>
          </tr>
          <tr>
            <th></th>
            <th><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success btn-lg mt-5" %></th>
          </tr>
        </tbody>
      </table>
     </div>
   </div>
 </div>

app/views/admin/orders/_index.html.erb
<table class='table table-hover table-striped table-inverse'style="background-color:gainsboro;">

  <thead>
    <tr>
      <th nowrap>商品名</th>
      <th nowrap>単価(税込)</th>
      <th nowrap>数量</th>
      <th nowrap>小計</th>
      <th nowrap>製作ステータス</th>
      <th></th>
    </tr>
  </thead>

  <% @order_items.each do |order_item| %>
    <tbody>
      <tr>
        <td nowrap><%= order_item.item.name  %></td>
        <td nowrap><%= order_item.tax_included_price.to_s(:delimited) %></td>
        <td nowrap><%= order_item.amount %></td>
        <td nowrap><%= order_item.subtotal.to_s(:delimited) %></td>
        <td nowrap>
        <%= form_with model: order_item, url: admin_order_item_path(order_item.id), method: :patch, local: true do |f| %>
        <%= f.select :making_status, OrderItem.making_statuses.keys.map {|k| [I18n.t("enums.order_item.making_status.#{k}"), k]}, class: "making_status" %>
        <%= f.submit "更新",class:"btn btn-success" %>
        <% end %>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/admin/orders/show.html.erb
<div class='container px-5 px-sm-0'>
  <div style ="color:green;"><%= flash[:notice] %></div>
  <div class='row'>
    <div class= "pt-2 ml-4 col-md-7 col-sm-6" style="font-size: 20px;">
      <span style="background-color:gainsboro"><strong>　注文履歴詳細　</strong></span>

      <div class='px-5 px-sm-0'>
        <div class='row'>
          <div class="mt-3"><strong>購入者</strong></div>
          <div class="mt-3 ml-5"><%= @order.customer.full_name %></div>
        </div>

        <div class='row'>
          <div class="mt-3"><strong>注文日</strong></div>
          <div class="mt-3 ml-5"><%= @order.created_at.strftime("%Y-%m-%d") %></div>
        </div>

        <div class='row'>
          <div class="mt-3"><strong>配送先</strong></div>
          <div class="mt-3 ml-5"><%= @order.ship_address %></div>
        </div>

        <div class='row'>
          <div class="mt-3"><strong>支払い方法</strong></div>
          <div class="mt-3 ml-5"><%= @order.payment_method_i18n %></div>
        </div>

        <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch, local: true do |f| %>
        <div class='row'>
          <div class="mt-3"><strong>注文ステータス</strong></div>
            <div class="mt-3 ml-5"><%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]}, class: "order_status" %></div>
            <div class="mt-3 ml-3 col-3"><%= f.submit "更新" , class: "btn btn-success" %></div>
        </div>
        <% end %>
    </div>
    </div>
    </div>
      <div class='container mt-4 px-5 px-sm-0 '>
        <div class='row'>
          <div class="col-7"><%= render 'index', order_item: @order_item %></div>

          <div class="col-5 justify-content-end clearfix float-right d-flex align-items-end"style="font-size: 20px;">
            <table>
              <th></th>
              <tr>
                <td style="font-weight: bolder;">商品合計</td>
                <td>:<%= @order.total_payment.round.to_s(:delimited) %>円</td>
              </tr>
                <tr>
                <td style="font-weight: bolder;">送料</td>
                <td>:<%= @order.postage %>円</td>
              </tr>
              <tr>
                <td style="font-weight: bolder;">請求合計金額</td>
                <td style="font-weight: bolder;">:<%= @order.total_price.to_s(:delimited) %>円</td>
              </tr>
            </table>
          </div>
          </div>
      </div>

</div>