config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }

  root "public/homes#top"

  namespace :admin do
    resources :orders,only:[:show, :update]
    resources :customers,only:[:show, :index, :edit, :update]
    resources :genres,only:[:index, :create, :edit, :update]
    resources :items,only:[:new, :index, :show, :create, :edit, :update]
    resources :order_items,only:[:update]
    root "homes#top"
  end

  namespace :public do
    resources :shipping_addresses,only:[:index, :create, :edit, :update,:destroy]
    get 'orders/finish'
    post 'orders/check'
    resources :orders,only:[:new, :index, :create, :show]
    delete 'cart_items/destroy_all'
    resources :cart_items,only:[:index, :create, :update, :destroy]
    resource :customers,only:[:show, :edit]
    patch "customers" => "customers#update", as: "customer"
    get 'customers/check'
    patch 'customers/out'
    get 'items/search'
    resources :items,only:[:show, :index]
    get 'homes/about'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  has_one_attached :image
  belongs_to :item

def tax_include_price
  (item.tax_free_price*1.1).round(0)
end

def subtotal
  tax_include_price*amount
end

def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
end

  private
  def cart_item_params
      params.require(:cart_item).permit(:item_id, :amount)
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :shipping_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  def full_name
    "#{last_name} #{first_name}"
  end
  
  def full_name_kana
    "#{last_name_kana} #{first_name_kana}"
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_one_attached :image
  has_many :cart_items , dependent: :destroy
  has_many :order_items , dependent: :destroy


  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def tax_include_price
    (tax_free_price*1.1).round(0)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items,dependent: :destroy
  
  def total_price
    total_payment + 800
  end

  def ship_address
    "〒 #{post_code} #{address} #{to_name}"
  end

  enum order_status: {
    wait_deposit: 0, payment_confirm: 1, production: 2, ship_preparation: 3, ship_completion: 4
  }

  enum payment_method: {
    credit_card: 0, transfer: 1
  }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: {
     not_startable: 0, wait_product: 1, in_product: 2, finish_product: 3
  }
  
  def tax_included_price
    (purchace_price*1.1).round(0)
  end
  
  def subtotal
    tax_included_price*amount
  end

  def tax_include_price
    (purchace_price*1.1).round(0)
  end

  def s_total
    tax_include_price*amount
  end

end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord

  belongs_to :customer
  
  validates :post_code,presence:true,length:{minimum: 7, maximum: 7}
  validates :address ,presence:true
  validates :name,presence:true

  def ship_address
  '〒' + post_code + ' ' + address + ' ' + name
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
    @genres = Genre.page(params[:page])
  end
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to request.referrer
  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end


  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
    @orders = Order.page(params[:page])
    @amount = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def index
      @items = Item.all
      @items = Item.page(params[:page])
    end

    def new
      @item = Item.new
      @genres = Genre.all

    end

    def show
      @item = Item.find(params[:id])
      @genre = @item.genre
    end

    def create
      @item = Item.new(item_params)
      @item.save
      redirect_to admin_item_path(@item.id)
    end

    def edit
      @item = Item.find(params[:id])
      @genres = Genre.all
    end

    def update
      @item = Item.find(params[:id])
      @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    end

    private

    def item_params
      params.require(:item).permit(:image, :name, :introduction, :genre_id, :tax_free_price, :sales_status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<div style="height: 100px; width: 100%;"></div>

app/views/layouts/_header.html.erb
    <header class="shadow-sm  bg-white">
      <nav class="navbar navbar-expand-lg navbar-light ">
        <div class="container">

          <a class="navbar-brand text-dark" href="/"><img src="/assets/logo1.jpg" alt="", width="200", height="40"></a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">

                <% if customer_signed_in? %>

                  <span class="text-center mr-5">ようこそ、<%= current_customer.last_name %>さん！</span>

                  <li class="nav-item ">

                    <%= link_to"マイページ",public_customers_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"商品一覧",public_items_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"カート",public_cart_items_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"ログアウト",destroy_customer_session_path,method: :delete,class: 'nav-link text-dark'%>
                  </li>

                <% elsif admin_signed_in? %>
                 <li class="nav-item ">
                    <%= link_to"商品一覧",admin_items_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"会員一覧",admin_customers_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"注文履歴一覧",admin_root_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"ジャンル一覧",admin_genres_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"ログアウト",destroy_admin_session_path,method: :delete,class: 'nav-link text-dark'%>
                  </li>

                <% else %>
                  <li class="nav-item ">
                  <%= link_to"About",public_homes_about_path,class: 'nav-link text-dark'%>
                 </li>

                 <li class="nav-item ">
                    <%= link_to"商品一覧",public_items_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"新規登録",new_customer_registration_path,class: 'nav-link text-dark'%>
                  </li>

                  <li class="nav-item ">
                    <%= link_to"ログイン",new_customer_session_path,class: 'nav-link text-dark'%>
                  </li>

                  <li><%= link_to "Admin用", new_admin_session_path, class:"btn btn-light" %></li>

                <% end %>
              </ul>
            </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="mt-4"></div>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>